// ============================================================
// ARKZEN ENGINE — TYPE DEFINITIONS v5.1
// v5.1: Added ArkzenCustomRoute + customRoutes to ParsedTatemono
//       Supports @arkzen:routes blocks — lightweight custom endpoints
//       with no model/database required. Used for simulate routes,
//       health checks, webhooks, and any one-off API handlers.
// ============================================================

export interface ArkzenMeta {
  name: string
  version: string
  description: string
  auth: boolean
  dependencies: string[]
}

export interface ArkzenConfigOverride {
  modal?: {
    borderRadius?: string
    backdrop?: string
    animation?: string
  }
  toast?: {
    position?: string
    duration?: number
    style?: string
  }
  table?: {
    striped?: boolean
    hoverable?: boolean
    border?: string
  }
  breadcrumb?: {
    separator?: string
    style?: string
  }
  dialog?: {
    size?: string
    animation?: string
  }
  layout?: {
    guest?: {
      className?: string
      container?: string
    }
    auth?: {
      className?: string
      container?: string
    }
    [customLayout: string]: {
      className?: string
      container?: string
    } | undefined
  }
}

export interface ArkzenColumn {
  type: string
  length?: number
  nullable?: boolean
  default?: string | number | boolean
  unique?: boolean
  primary?: boolean
  autoIncrement?: boolean
  foreign?: string
  onDelete?: string
  precision?: number
  scale?: number
  unsigned?: boolean
}

export interface ArkzenIndex {
  columns: string[]
  unique: boolean
}

export interface ArkzenSeederItem {
  [key: string]: string | number | boolean | null
}

export interface ArkzenDatabase {
  table: string
  timestamps: boolean
  softDeletes: boolean
  columns: Record<string, ArkzenColumn>
  indexes?: ArkzenIndex[]
  seeder?: {
    count: number
    data?: ArkzenSeederItem[]
  }
}

export interface ArkzenEndpointValidation {
  [field: string]: string
}

export interface ArkzenEndpointQuery {
  [param: string]: string
}

export interface ArkzenEndpointResponse {
  type: 'paginated' | 'single' | 'collection' | 'message'
  resource?: string
  value?: string
}

export interface ArkzenEndpoint {
  method: 'GET' | 'POST' | 'PUT' | 'PATCH' | 'DELETE'
  route: string
  description: string
  validation?: ArkzenEndpointValidation
  query?: ArkzenEndpointQuery
  response: ArkzenEndpointResponse
}

export interface ArkzenApi {
  model: string
  controller: string
  prefix: string
  middleware: string[]
  endpoints: Record<string, ArkzenEndpoint>
  resource?: boolean
  policy?: boolean
  factory?: boolean
}

// ─────────────────────────────────────────────
// CUSTOM ROUTES — v5.1
// Lightweight one-off endpoints with no model or database.
// Declared via @arkzen:routes blocks in the tatemono DSL.
//
// Example DSL:
//   /* @arkzen:routes
//   controller: SimulateController
//   middleware: []
//   routes:
//     - method: GET
//       route: /api/errors-test/simulate/{code}
//       handler: simulate
//   */
//
// The controller is auto-generated by CustomRouteBuilder.
// Handler method receives all route parameters as variadic $params.
// ─────────────────────────────────────────────

export interface ArkzenCustomRouteEntry {
  method: 'GET' | 'POST' | 'PUT' | 'PATCH' | 'DELETE'
  route: string
  handler: string
}

export interface ArkzenCustomRoute {
  controller: string
  middleware: string[]
  routes: ArkzenCustomRouteEntry[]
}

// NEW: Interfaces for parsed named sections
export interface ArkzenStore {
  [key: string]: unknown
}

export interface ArkzenRealtime {
  [key: string]: unknown
}

export interface ArkzenEvent {
  [key: string]: unknown
}

export interface ArkzenJob {
  [key: string]: unknown
}

export interface ArkzenNotification {
  [key: string]: unknown
}

export interface ArkzenMail {
  [key: string]: unknown
}

export interface ArkzenConsole {
  signature: string
  description: string
  schedule?: string
  [key: string]: unknown
}

export interface ArkzenSection {
  raw: string
  start: number
  end: number
}

export type ArkzenPageLayout = 'guest' | 'auth' | string

export interface ArkzenPage {
  name: string
  layout: ArkzenPageLayout
  raw: string
  start: number
  end: number
}

// ─────────────────────────────────────────────
// ERROR HANDLERS — Next.js segment-scoped files
// @arkzen:error:404 → app/{name}/not-found.tsx
// @arkzen:error:500 → app/{name}/error.tsx
// ─────────────────────────────────────────────

export type ArkzenErrorHandlerType = '404' | '500'

export interface ArkzenErrorHandler {
  type: ArkzenErrorHandlerType
  raw: string  // the ErrorScreen (or custom) component raw code
}

export interface ArkzenLayout {
  name: string
  raw: string
  start: number
  end: number
}

export interface ParsedTatemono {
  filePath: string
  fileName: string
  meta: ArkzenMeta
  config?: ArkzenConfigOverride

  databases:    ArkzenDatabase[]
  apis:         ArkzenApi[]
  customRoutes: ArkzenCustomRoute[]   // ← v5.1: lightweight one-off endpoints
  pages:        ArkzenPage[]
  layouts:      ArkzenLayout[]

  errorHandlers: ArkzenErrorHandler[]

  stores:        ArkzenStore[]
  realtimes:     ArkzenRealtime[]
  events:        ArkzenEvent[]
  jobs:          ArkzenJob[]
  notifications: ArkzenNotification[]
  mails:         ArkzenMail[]
  consoles:      ArkzenConsole[]
  components:    ArkzenSection[]

  animation?: ArkzenSection
}

export interface ArkzenRegistry {
  engine: string
  project: string
  modules: ArkzenRegistryEntry[]
}

export interface ArkzenRegistryEntry {
  name: string
  version: string
  status: 'active' | 'inactive' | 'error'
  filePath: string
  pages: string[]
  registered: string
  lastUpdated: string
  auth?: boolean   // ← v5.1: indicates auth:true in meta
}

export interface BuildResult {
  success: boolean
  tatemono: string
  steps: BuildStep[]
  errors: string[]
}

export interface BuildStep {
  name: string
  status: 'success' | 'failed' | 'skipped'
  message: string
}

export interface ValidationResult {
  valid: boolean
  errors: string[]
  warnings: string[]
  summary?: {
    tables: string[]
    pages: string[]
    resources: string[]
  }
}