<?php

// ============================================================
// ARKZEN ENGINE — AUTH SETUP BUILDER
// Installs Laravel Sanctum for real API token authentication.
// Called once by setup.js — not per tatemono.
//
// What it does:
//   1. Publishes Sanctum config + migration
//   2. Runs Sanctum migration (personal_access_tokens table)
//   3. Adds HasApiTokens trait to User model
//   4. Registers role middleware alias in app.php
// ============================================================

namespace App\Arkzen\Builders;

use Illuminate\Support\Facades\File;
use Illuminate\Support\Facades\Artisan;
use Illuminate\Support\Facades\Log;

class AuthBuilder
{
    // ─────────────────────────────────────────────
    // SETUP — run once during node setup.js
    // ─────────────────────────────────────────────

    public static function setup(): void
    {
        self::publishSanctum();
        self::patchUserModel();
        self::ensureAuthRoutes();
        Log::info("[Arkzen Auth] ✓ Auth setup complete");
    }

    // ─────────────────────────────────────────────
    // PUBLISH SANCTUM
    // ─────────────────────────────────────────────

    private static function publishSanctum(): void
    {
        // Publish Sanctum migrations
        Artisan::call('vendor:publish', [
            '--provider' => 'Laravel\\Sanctum\\SanctumServiceProvider',
            '--force'    => true,
        ]);

        // Run Sanctum migration
        Artisan::call('migrate', ['--force' => true]);

        Log::info("[Arkzen Auth] ✓ Sanctum published and migrated");
    }

    // ─────────────────────────────────────────────
    // PATCH USER MODEL
    // Adds HasApiTokens if not already present
    // ─────────────────────────────────────────────

    private static function patchUserModel(): void
    {
        $userModelPath = app_path('Models/User.php');

        if (!File::exists($userModelPath)) {
            Log::warning("[Arkzen Auth] ⚠ User model not found — skipping patch");
            return;
        }

        $content = File::get($userModelPath);

        if (str_contains($content, 'HasApiTokens')) {
            Log::info("[Arkzen Auth] ✓ User model already has HasApiTokens");
            return;
        }

        // Add use statement
        $content = str_replace(
            'use Illuminate\Foundation\Auth\User as Authenticatable;',
            "use Illuminate\Foundation\Auth\User as Authenticatable;\nuse Laravel\Sanctum\HasApiTokens;",
            $content
        );

        // Add trait to class body
        $content = str_replace(
            'use HasFactory, Notifiable;',
            'use HasApiTokens, HasFactory, Notifiable;',
            $content
        );

        File::put($userModelPath, $content);
        Log::info("[Arkzen Auth] ✓ User model patched with HasApiTokens");
    }

    // ─────────────────────────────────────────────
    // ENSURE AUTH ROUTES EXIST
    // Creates routes/modules/auth.php with login/register/logout
    // ─────────────────────────────────────────────

    private static function ensureAuthRoutes(): void
    {
        $routePath = base_path('routes/modules/auth.php');

        if (File::exists($routePath)) {
            Log::info("[Arkzen Auth] ✓ Auth routes already exist");
            return;
        }

        self::generateAuthController();

        $content = <<<'PHP'
<?php

// ============================================================
// ARKZEN ENGINE — AUTH ROUTES
// Generated by AuthBuilder. Do not edit directly.
// Provides: login, register, logout, /me
// ============================================================

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Arkzen\ArkzenAuthController;

Route::middleware(['api'])->prefix('/api/auth')->group(function () {
    Route::post('/register', [ArkzenAuthController::class, 'register']);
    Route::post('/login',    [ArkzenAuthController::class, 'login']);
});

Route::middleware(['api', 'auth:sanctum'])->prefix('/api/auth')->group(function () {
    Route::post('/logout', [ArkzenAuthController::class, 'logout']);
    Route::get('/me',      [ArkzenAuthController::class, 'me']);
});
PHP;

        File::ensureDirectoryExists(base_path('routes/modules'));
        File::put($routePath, $content);
        Log::info("[Arkzen Auth] ✓ Auth routes created");
    }

    // ─────────────────────────────────────────────
    // GENERATE AUTH CONTROLLER
    // ─────────────────────────────────────────────

    private static function generateAuthController(): void
    {
        $path = app_path('Http/Controllers/Arkzen/ArkzenAuthController.php');

        if (File::exists($path)) {
            return;
        }

        $content = <<<'PHP'
<?php

// ============================================================
// ARKZEN ENGINE — AUTH CONTROLLER
// Handles register, login, logout, /me
// Uses Laravel Sanctum for real token-based auth
// ============================================================

namespace App\Http\Controllers\Arkzen;

use Illuminate\Routing\Controller;
use Illuminate\Http\Request;
use Illuminate\Http\JsonResponse;
use Illuminate\Support\Facades\Hash;
use Illuminate\Validation\ValidationException;
use App\Models\User;

class ArkzenAuthController extends Controller
{
    // ─────────────────────────────────────────────
    // REGISTER
    // ─────────────────────────────────────────────

    public function register(Request $request): JsonResponse
    {
        $validated = $request->validate([
            'name'     => 'required|string|max:255',
            'email'    => 'required|email|unique:users,email',
            'password' => 'required|string|min:8|confirmed',
        ]);

        $user = User::create([
            'name'     => $validated['name'],
            'email'    => $validated['email'],
            'password' => Hash::make($validated['password']),
        ]);

        $token = $user->createToken('arkzen-token')->plainTextToken;

        return response()->json([
            'user'  => $user,
            'token' => $token,
        ], 201);
    }

    // ─────────────────────────────────────────────
    // LOGIN
    // ─────────────────────────────────────────────

    public function login(Request $request): JsonResponse
    {
        $validated = $request->validate([
            'email'    => 'required|email',
            'password' => 'required|string',
        ]);

        $user = User::where('email', $validated['email'])->first();

        if (!$user || !Hash::check($validated['password'], $user->password)) {
            throw ValidationException::withMessages([
                'email' => ['The provided credentials are incorrect.'],
            ]);
        }

        // Revoke old tokens and issue fresh one
        $user->tokens()->delete();
        $token = $user->createToken('arkzen-token')->plainTextToken;

        return response()->json([
            'user'  => $user,
            'token' => $token,
        ]);
    }

    // ─────────────────────────────────────────────
    // LOGOUT
    // ─────────────────────────────────────────────

    public function logout(Request $request): JsonResponse
    {
        $request->user()->currentAccessToken()->delete();

        return response()->json(['message' => 'Logged out successfully']);
    }

    // ─────────────────────────────────────────────
    // ME — current user
    // ─────────────────────────────────────────────

    public function me(Request $request): JsonResponse
    {
        return response()->json($request->user());
    }
}
PHP;

        File::ensureDirectoryExists(app_path('Http/Controllers/Arkzen'));
        File::put($path, $content);
        Log::info("[Arkzen Auth] ✓ ArkzenAuthController created");
    }
}