// ============================================================
// ARKZEN ENGINE — REGISTRY v5.1
// v5.1: Automatically generates auth-tatemonos.ts manifest
//       for middleware to consume. No more manual AUTH_TATEMONOS list.
// ============================================================

import * as fs from 'fs'
import * as path from 'path'
import type { ArkzenRegistry, ArkzenRegistryEntry, ParsedTatemono } from '../types'

const REGISTRY_PATH = path.resolve(process.cwd(), 'arkzen.json')
const AUTH_MANIFEST_PATH = path.resolve(process.cwd(), 'arkzen', 'generated', 'auth-tatemonos.ts')

export function getRegistry(): ArkzenRegistry {
  if (!fs.existsSync(REGISTRY_PATH)) {
    return createEmptyRegistry()
  }
  const raw = fs.readFileSync(REGISTRY_PATH, 'utf-8')
  return JSON.parse(raw) as ArkzenRegistry
}

function writeRegistry(registry: ArkzenRegistry): void {
  fs.writeFileSync(REGISTRY_PATH, JSON.stringify(registry, null, 2), 'utf-8')
}

function createEmptyRegistry(): ArkzenRegistry {
  const registry: ArkzenRegistry = {
    engine: '5.1.0',
    project: path.basename(process.cwd()),
    modules: [],
  }
  writeRegistry(registry)
  return registry
}

// ─────────────────────────────────────────────
// AUTH MANIFEST GENERATION
// Writes a TypeScript file exporting the array of
// tatemonos that have auth: true.
// ─────────────────────────────────────────────

function rebuildAuthManifest(): void {
  const registry = getRegistry()
  const authModules = registry.modules
    .filter(m => m.status === 'active')
    .map(m => m.name)
    // We need to know which ones actually have auth:true.
    // Since the registry entry doesn't store auth flag,
    // we must read each tatemono's meta during update.
    // Instead, we maintain a separate auth set in memory
    // and write it when any tatemono changes.
  
  // For simplicity, we'll rely on the update process to pass
  // the auth flag. We'll add an optional `auth` field to
  // ArkzenRegistryEntry in a future version. For now,
  // we'll build the list by scanning the registry modules
  // that have auth routes generated (heuristic: they have
  // a generated AuthController). But that's backend-side.
  // Cleaner: we pass the auth flag from updateRegistry.
}

// We'll modify updateRegistry to accept the auth flag and rebuild manifest.
export function updateRegistry(tatemono: ParsedTatemono): void {
  const registry = getRegistry()
  const now = new Date().toISOString()

  const existingIndex = registry.modules.findIndex(m => m.name === tatemono.meta.name)

  const entry: ArkzenRegistryEntry = {
    name:        tatemono.meta.name,
    version:     tatemono.meta.version,
    status:      'active',
    filePath:    tatemono.filePath,
    pages:       tatemono.pages.map(p => p.name),
    registered:  existingIndex === -1 ? now : registry.modules[existingIndex].registered,
    lastUpdated: now,
    // v5.1: store auth flag for manifest generation
    auth:        tatemono.meta.auth,
  }

  if (existingIndex === -1) {
    registry.modules.push(entry)
    console.log(`[Arkzen Registry] ✓ New tatemono registered: ${tatemono.meta.name} (${entry.pages.length} page(s), auth: ${tatemono.meta.auth})`)
  } else {
    registry.modules[existingIndex] = entry
    console.log(`[Arkzen Registry] ✓ Tatemono updated: ${tatemono.meta.name} (${entry.pages.length} page(s), auth: ${tatemono.meta.auth})`)
  }

  writeRegistry(registry)

  // Rebuild the auth manifest file
  writeAuthManifest(registry)
}

function writeAuthManifest(registry: ArkzenRegistry): void {
  const authTatemonos = registry.modules
    .filter(m => m.status === 'active' && (m as any).auth === true)
    .map(m => m.name)

  const dir = path.dirname(AUTH_MANIFEST_PATH)
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true })
  }

  const content = `// ============================================================
// ARKZEN GENERATED — Auth Tatemonos Manifest
// Auto-generated by registry.ts. DO NOT EDIT MANUALLY.
// Contains all tatemonos with auth: true.
// ============================================================

export const AUTH_TATEMONOS: string[] = ${JSON.stringify(authTatemonos, null, 2)};
`

  fs.writeFileSync(AUTH_MANIFEST_PATH, content, 'utf-8')
  console.log(`[Arkzen Registry] ✓ Auth manifest updated: ${authTatemonos.length} tatemonos`)
}

export function removeFromRegistry(tatemononName: string): void {
  const registry = getRegistry()
  const before = registry.modules.length
  registry.modules = registry.modules.filter(m => m.name !== tatemononName)

  if (registry.modules.length < before) {
    writeRegistry(registry)
    writeAuthManifest(registry)
    console.log(`[Arkzen Registry] ✓ Removed from registry: ${tatemononName}`)
  }
}

// v5: get registry entry to build full remove payload
export function getRegistryEntry(tatemononName: string): ArkzenRegistryEntry | undefined {
  return getRegistry().modules.find(m => m.name === tatemononName)
}

export function setRegistryError(tatemononName: string, error: string): void {
  const registry = getRegistry()
  const entry = registry.modules.find(m => m.name === tatemononName)
  if (entry) {
    entry.status = 'error'
    writeRegistry(registry)
    // Don't update manifest on error state change? Maybe keep but mark inactive.
  }
}

export function isRegistered(tatemononName: string): boolean {
  return getRegistry().modules.some(m => m.name === tatemononName)
}

export function getActiveModules(): ArkzenRegistryEntry[] {
  return getRegistry().modules.filter(m => m.status === 'active')
}

export function listRegistry(): void {
  const registry = getRegistry()
  console.log(`\n[Arkzen Registry] Project: ${registry.project} | Engine: ${registry.engine}`)
  console.log(`[Arkzen Registry] Active tatemonos: ${registry.modules.length}`)
  registry.modules.forEach(m => {
    const icon = m.status === 'active' ? '✓' : m.status === 'error' ? '✗' : '○'
    const pages = m.pages?.join(', ') ?? ''
    const authFlag = (m as any).auth ? '🔐' : ''
    console.log(`  ${icon} ${m.name} v${m.version} — ${m.status} ${authFlag} [${pages}]`)
  })
}