// ============================================================
// ARKZEN ENGINE — MIDDLEWARE v1.2
// v1.2: Auth tatemonos list now auto-generated by the build
//       process. No manual array maintenance required.
// ============================================================

import { NextRequest, NextResponse } from 'next/server'
import { AUTH_TATEMONOS } from '@/arkzen/generated/auth-tatemonos'

// ─────────────────────────────────────────────
// PAGE CLASSIFICATIONS
// These only apply to tatemonos listed in AUTH_TATEMONOS.
// ─────────────────────────────────────────────

const GUEST_PAGES = [
  'login',
  'register',
  'forgot-password',
  'reset-password',
]

const AUTH_PAGES = [
  'dashboard',
  'settings',
  'profile',
]

// ─────────────────────────────────────────────
// MIDDLEWARE
// ─────────────────────────────────────────────

export function middleware(request: NextRequest) {
  const { pathname } = request.nextUrl
  const segments     = pathname.split('/').filter(Boolean)
  const tatemono     = segments[0]  // e.g. 'auth-test'
  const page         = segments[1]  // e.g. 'login', 'dashboard'

  // Not a tatemono route — let it through
  if (!tatemono || !page) return NextResponse.next()

  // Not an auth-enabled tatemono — always let it through
  if (!AUTH_TATEMONOS.includes(tatemono)) return NextResponse.next()

  // Read the per-tatemono auth cookie set by authStore on login
  const token = request.cookies.get(`arkzen-auth-${tatemono}`)?.value

  // Authenticated user trying to visit login/register → send to dashboard
  if (GUEST_PAGES.includes(page) && token) {
    return NextResponse.redirect(new URL(`/${tatemono}/dashboard`, request.url))
  }

  // Unauthenticated user trying to visit protected page → send to login
  if (AUTH_PAGES.includes(page) && !token) {
    return NextResponse.redirect(new URL(`/${tatemono}/login`, request.url))
  }

  return NextResponse.next()
}

// ─────────────────────────────────────────────
// MATCHER
// Runs on all routes except Next.js internals and the API.
// ─────────────────────────────────────────────

export const config = {
  matcher: ['/((?!_next|api|arkzen|static|favicon.ico).*)'],
}