<!DOCTYPE html>
<html>
<head><meta charset="UTF-8"><title>EndMail</title></head>
<body style="font-family: sans-serif; padding: 40px; color: #333;">
    <h2>EndMail</h2>
    <p style="color: #666; font-size: 12px;">Tatemono: mail-test</p>
    <hr>
    
    <hr>
    <p style="color: #999; font-size: 12px;">This email was generated by Arkzen.</p>
</body>
</html>
