<!DOCTYPE html>
<html>
<head><meta charset="UTF-8"><title>Your order has been confirmed</title></head>
<body style="font-family: sans-serif; padding: 40px; color: #333;">
    <h2>Your order has been confirmed</h2>
    <p style="color: #666; font-size: 12px;">Tatemono: mail-test</p>
    <hr>
    <p>{{ $order_id }}</p>
    <p>{{ $total }}</p>
    <p>{{ $customer_name }}</p>
    <hr>
    <p style="color: #999; font-size: 12px;">This email was generated by Arkzen.</p>
</body>
</html>
