<!DOCTYPE html>
<html>
<head><meta charset="UTF-8"><title>Reset your password</title></head>
<body style="font-family: sans-serif; padding: 40px; color: #333;">
    <h2>Reset your password</h2>
    <p style="color: #666; font-size: 12px;">Tatemono: mail-test</p>
    <hr>
    <p>{{ $reset_link }}</p>
    <p>{{ $expires_in }}</p>
    <hr>
    <p style="color: #999; font-size: 12px;">This email was generated by Arkzen.</p>
</body>
</html>
